// Code generated by mockery v2 (manual). DO NOT EDIT.
package mocks

import (
	"github.com/jacksonfernando/qbridge/internal/config"
	"github.com/stretchr/testify/mock"
)

// MockStorer is a mock implementation of config.Storer.
type MockStorer struct {
	mock.Mock
}

func (_m *MockStorer) GetDB(name string) (*config.Database, error) {
	ret := _m.Called(name)
	var r0 *config.Database
	if rf, ok := ret.Get(0).(func(string) *config.Database); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Database)
		}
	}
	return r0, ret.Error(1)
}

func (_m *MockStorer) AddDB(db config.Database) error {
	ret := _m.Called(db)
	return ret.Error(0)
}

func (_m *MockStorer) RemoveDB(name string) error {
	ret := _m.Called(name)
	return ret.Error(0)
}

func (_m *MockStorer) GetProfile(name string) (*config.Profile, error) {
	ret := _m.Called(name)
	var r0 *config.Profile
	if rf, ok := ret.Get(0).(func(string) *config.Profile); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Profile)
		}
	}
	return r0, ret.Error(1)
}

func (_m *MockStorer) AddProfile(p config.Profile) error {
	ret := _m.Called(p)
	return ret.Error(0)
}

func (_m *MockStorer) RemoveProfile(name string) error {
	ret := _m.Called(name)
	return ret.Error(0)
}

func (_m *MockStorer) UpdateProfile(p config.Profile) error {
	ret := _m.Called(p)
	return ret.Error(0)
}

func (_m *MockStorer) GetDatabases() []config.Database {
	ret := _m.Called()
	var r0 []config.Database
	if rf, ok := ret.Get(0).(func() []config.Database); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Database)
		}
	}
	return r0
}

func (_m *MockStorer) GetProfiles() []config.Profile {
	ret := _m.Called()
	var r0 []config.Profile
	if rf, ok := ret.Get(0).(func() []config.Profile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Profile)
		}
	}
	return r0
}

func (_m *MockStorer) Save() error {
	ret := _m.Called()
	return ret.Error(0)
}

// NewMockStorer creates a new instance of MockStorer.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	m := &MockStorer{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
